// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAzrnBo5pT1VnyYFj3Jb4uxgbZBze5fbU',
    appId: '1:411897634529:web:de3bbbc08cf73615f861a0',
    messagingSenderId: '411897634529',
    projectId: 'ttsante-2ef9f',
    authDomain: 'ttsante-2ef9f.firebaseapp.com',
    storageBucket: 'ttsante-2ef9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLQbfGgpo9BGWlyY3u65jDdSeTqbtjWTs',
    appId: '1:411897634529:android:53089c39bf6d612ff861a0',
    messagingSenderId: '411897634529',
    projectId: 'ttsante-2ef9f',
    storageBucket: 'ttsante-2ef9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbDUcsRRJV_fgMU_QDLD5PhdJWbBgQvw',
    appId: '1:411897634529:ios:5b569b7344eb24b3f861a0',
    messagingSenderId: '411897634529',
    projectId: 'ttsante-2ef9f',
    storageBucket: 'ttsante-2ef9f.firebasestorage.app',
    iosBundleId: 'com.example.applicationTelecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbDUcsRRJV_fgMU_QDLD5PhdJWbBgQvw',
    appId: '1:411897634529:ios:5b569b7344eb24b3f861a0',
    messagingSenderId: '411897634529',
    projectId: 'ttsante-2ef9f',
    storageBucket: 'ttsante-2ef9f.firebasestorage.app',
    iosBundleId: 'com.example.applicationTelecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAzrnBo5pT1VnyYFj3Jb4uxgbZBze5fbU',
    appId: '1:411897634529:web:56369e7b1672796bf861a0',
    messagingSenderId: '411897634529',
    projectId: 'ttsante-2ef9f',
    authDomain: 'ttsante-2ef9f.firebaseapp.com',
    storageBucket: 'ttsante-2ef9f.firebasestorage.app',
  );
}
